/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#09090b",
        surface: "#18181b",
        border: "#27272a",
        canvas: "var(--surface-canvas)",
        workbench: "var(--surface-workbench)",
        panel: "var(--surface-panel)",
        overlay: "var(--surface-overlay)",
        modal: "var(--surface-modal)",
        elevated: "var(--surface-elevated)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-hover": "var(--surface-hover)",
        "surface-active": "var(--surface-active)",
        "border-hairline": "var(--border-hairline)",
        "border-accent": "var(--border-accent)",
        "border-focus": "var(--border-focus)",
      },
      borderColor: {
        hairline: "var(--border-hairline)",
        subtle: "var(--border-subtle)",
        strong: "var(--border-strong)",
        accent: "var(--border-accent)",
        focus: "var(--border-focus)",
      },
      textColor: {
        primary: "var(--text-primary)",
        secondary: "var(--text-secondary)",
        muted: "var(--text-muted)",
        accent: "var(--text-accent)",
      },
      borderRadius: {
        pill: "var(--radius-xl)",
        dropdown: "var(--dropdown-radius-outer)",
        modal: "var(--radius-2xl)",
        card: "var(--radius-lg)",
        panel: "var(--radius-xl)",
      },
      boxShadow: {
        "elevation-1": "var(--shadow-elevation-1)",
        "elevation-2": "var(--shadow-elevation-2)",
        "elevation-3": "var(--shadow-elevation-3)",
      },
      fontFamily: {
        sans: [
          "var(--ide-ui-font)",
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          "var(--ide-mono-font)",
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
    },
  },
  plugins: [],
}
